### ISSUE TITLE
Implement standard thread libraries with win32 api

### ISSUE THREAD

**Issue by rongjiecomputer** [mingw-w64/mingw-w64#1]
Is there any plan to implement standard thread libraries with win32 api for win32 thread model? I know posix thread model uses winpthread for standard thread libraries, but it is really heavyweight and requires libwinpthread-1.dll to be distributed.

[mingw-std-threads](https://github.com/meganz/mingw-std-threads) has a simple implementation for `<thread>`, `<mutex>` and `<condition_variable>`. It is really lightweight and works quite well, but the header files introduce many macros from `<windows.h>` and several things specified in the standard like hash class for `std::thread::id` are omitted.

I tried to modified their works by separating `<windows.h>` from the header files and also implement things they omitted. But since I am not very familiar with multi-threading myself, so far I only able to get `<thread>` to work.

It will be nice if mingw-w64 can collaborate with mingw-std-threads to make this happen.

**Comment by lhmouse** [comment]
I wouldn't suggest use of _mingw-std-threads_ because it is essentially **a separated implementation of the standard library** in addition to _libstdc++_ itself.

In reality, both _libstdc++_ for gcc and _libc++_ for clang build their standard thread stuff on sort of abstraction layers. libstdc++ implements `std::mutex`, `std::condition_variable`, `std::thread` and so on basing on interfaces described [here](https://gcc.gnu.org/viewcvs/gcc/trunk/libgcc/gthr.h?view=markup), while libc++ uses a similar set of functions and types whose names begin with `__libcpp_`.

As you can see, the `win32` thread model [here](https://gcc.gnu.org/viewcvs/gcc/trunk/libgcc/config/i386/gthr-win32.c?view=markup) is maintained by GCC people. Because of lack of condition variable support it doesn't enable C++11 thread using `#define __GTHREADS_CXX0X 1`. Nevertheless it isn't mingw-w64 people that are to complete it. It is GCC maintainers that are to complete it.

I just wouldn't bother myself to fix the `win32` thread model up so I have created a new thread model basing on a library that implements all `__gthread_*` functions [here](https://github.com/lhmouse/mcfgthread/blob/master/src/env/gthread.h). There are a few [documents](https://github.com/lhmouse/mcfgthread/wiki) describing how it works and how to work with it.

**Comment by RoyiAvital** [comment]
@lhmouse , Does this issue has anything to do with the reason AVX and AVX2 aren't supported on Windows 64 Bit?

**Comment by lhmouse** [comment]
@RoyiAvital No. You have to pass `-mavx` or `-march=sandybridge` to GCC for AVX, and `-mavx2` or `-march=haswell` for AVX2. By default GCC targets the generic x64 architecture where only SSE and SSE2 is guaranteed.

**Comment by RoyiAvital** [comment]
@lhmouse ,
I meant that MinGW64 using GCC can't align the AVX code properly to be compatible with Windows 64 Bit.

Have a look at - https://github.com/Alexpux/MSYS2-packages/issues/1209#issuecomment-379547589.

**Comment by lhmouse** [comment]
It is a GCC bug. mingw-w64, being the CRT, is irresponsible for GCC bugs.

**Comment by RoyiAvital** [comment]
I thought the Windows comparability of GCC is done by the MinGW64 people.

Thank You.

**Comment by lhmouse** [comment]
Did you mean _compatibility_ ? Well, the calling convention is specified by MS. We can do nothing but follow it.

**Comment by RoyiAvital** [comment]
I'm not an expert on how compilers work.
But I though that all changes into GCC in order to make it generate Windows Compatible code is done by the MinGW64 project.

Anyhow, maybe knowledgeable people from MinGW64 could collaborate with GCC people to solve this.

**Comment by RoyiAvital** [comment]
See here:

https://gcc.gnu.org/bugzilla/show_bug.cgi?id=54412

If you have input it would be great.
Also if you could notify jon_y and ktietz about it.

**Comment by lhmouse** [comment]
I did. Feel free to join the talk on OFTC.  <irc://irc.oftc.net/#mingw-w64>

**Comment by RoyiAvital** [comment]
OK, Just to add information, I think this comment is important - https://stackoverflow.com/questions/30928265/mingw64-is-incapable-of-32-byte-stack-alignment-required-for-avx-on-windows-x64?noredirect=1#comment86499640_30928265.
